[package]
name = "life"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
serde = { version = "1.0.219", features = ["derive"] }

[lints.rust]
dead_code = "allow"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = "warn"
nursery = "warn"
